### ISSUE TITLE
Contracts not getting mapped to epgs

### ISSUE THREAD

**Issue by jorgenspange** [terraform-cisco-modules/easy-aci#1] opened 2023-09-08 12:01 UTC
Greetings!

Seems like there's something causing contracts not to get mapped to epgs.
Here's my code:

Contract config:
````yaml
        - contract_type: standard
          description: Contract for management traffic towards l3out
          name: company-mgt:l3out-ct
          subjects:
            - action: permit
              apply_both_directions: true
              filters:
                - "any"
              name: company_mgt_l3out_fltr
      filters:
        - description: default
          filter_entries:
            - description: default
              name: default
              stateful: false
          name: any

````
And here's my epg:

````yaml
          external_epgs:
            - name: company_mgt_l3out_ext_epg
              contracts:
                - name: company-mgt:l3out-ct
                  contract_type: provided
````

Best regards

**Comment by scotttyso** [comment] 2023-09-10 14:44
@jorgenspange , interesting.  I am not sure without testing what the root cause is.. I am out of office right now but will look later next week when I am back in the office.

**Comment by scotttyso** [comment] 2023-09-14 15:54
@jorgenspange 

What version of the module are you using?  I just tested with 3.0.4 and it applied the contract to the External EPG

```yaml
      l3outs:
      - description: Asgard Production L3Out
        enable_bgp: true
        external_epgs:
        - contracts:
          - contract_type: consumed
            name: testing_123
          - contract_type: provided
            name: testing_123
          description: Asgard Prod
          name: prod
          preferred_group_member: true
          subnets:
          - external_epg_classification:
              external_subnets_for_external_epg: true
            subnets:
            - 0.0.0.0/1
            - 128.0.0.0/1
```


```terraform
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.built_in_tenants["common"].aci_rest_managed.external_epg_contracts["asgard-prod:prod:provided:testing_123"] will be created
  + resource "aci_rest_managed" "external_epg_contracts" {
      + class_name = "fvRsProv"
      + content    = {
          + "prio"         = "unspecified"
          + "tnVzBrCPName" = "testing_123"
        }
      + dn         = "uni/tn-common/out-asgard-prod/instP-prod/rsprov-testing_123"
      + id         = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

```terraform
tyscott@TYSCOTT-DESKTOP:~/terraform-cisco-modules/easy-aci/RICH/TEST$ tfa
module.built_in_tenants["common"].aci_rest_managed.external_epg_contracts["asgard-prod:prod:provided:testing_123"]: Creating...
module.built_in_tenants["common"].aci_rest_managed.external_epg_contracts["asgard-prod:prod:provided:testing_123"]: Creation complete after 0s [id=uni/tn-common/out-asgard-prod/instP-prod/rsprov-testing_123]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:
```

I am looking for what is configured in the main.tf under the built_in_tenants and tenants modules:

```terraform
module "built_in_tenants" {
  depends_on = [module.access]
  # source     = "../../../terraform-aci-tenants"
  source  = "terraform-cisco-modules/tenants/aci"
  version = "3.0.4"
  for_each = {
    for v in lookup(local.model, "tenants", []) : v.name => v if length(regexall("^(common|infra|mgmt)$", v.name)) > 0
  }
  model = merge(each.value, lookup(local.model, "templates", {}), {
    aaep_to_epgs    = {}
    global_settings = local.global_settings
    switch          = {}
    templates       = lookup(local.model, "templates", {})
  })
  tenant           = each.key
  tenant_sensitive = local.tenant_sensitive
}
```

```terraform
module "tenants" {
  depends_on = [module.built_in_tenants]
  #source     = "../../../terraform-aci-tenants"
  source  = "terraform-cisco-modules/tenants/aci"
  version = "3.0.4"
  for_each = {
    for v in lookup(local.model, "tenants", []) : v.name => v if length(regexall("^(common|infra|mgmt)$", v.name)) == 0
  }
  model = merge(each.value, lookup(local.model, "templates", {}), {
    aaep_to_epgs    = {}
    global_settings = local.global_settings
    switch          = {}
    templates       = lookup(local.model, "templates", {})
  })
  tenant           = each.key
  tenant_sensitive = local.tenant_sensitive
}
```

**Comment by jorgenspange** [comment] 2023-09-14 19:15
Hey,

Thank you for following up!

We are running with 2.1.5 at the moment, as we are running with APIC on version 5.2(7g).

Also did you verify in the gui that the contract got applied, because for me it looked good when I ran tf apply, but nothing seemed to happen in the gui.

Br
Jørgen

**Comment by scotttyso** [comment] 2023-09-15 04:53
Yes, I can confirm the contracts are applied in the APIC.

3.0.4 is also compatible with 5.2(7g).  but there are some changes between 3.0.4 and 2.1.5.  Namely the global_settings.eza.yaml, where I have moved all the non-sensitive variables.  If you have any challenges migrating from 2.1.5 to 3.0.4 let me know and I can help to talk you through migration from 2.1.5 to 3.0.4 without tainting the state files.

**Comment by jorgenspange** [comment] 2023-09-15 05:57
Okey awesome. 

If you have the opportunity to take me through that would be much appreciated.

Br

**Comment by jorgenspange** [comment] 2023-09-19 12:29
Good day @scotttyso,

We have upgrade the modules now, stumbled upon one issue:
![image](https://github.com/terraform-cisco-modules/easy-aci/assets/75736500/706da13d-5341-4541-94d8-fe9a5d1fdded)

In policies-switch.tf in the access module we commented out the #delayRestoreTmr, this fixed the error, but we had to clone down the module into our repo and fix it locally.

Does it exist another way around this?

```go
/*_____________________________________________________________________________________________________________________

API Information:
 - Class: "vpcInstPol"
 - Distinguished Name: "uni/fabric/vpcInst-{name}"
GUI Location:
 - Fabric -> Access Policies -> Policies -> Switch -> VPC Domain -> Create VPC Domain Policy
_______________________________________________________________________________________________________________________
*/
resource "aci_rest_managed" "vpc_domain_policy" {
  for_each = {
    for v in [local.vpc_domain] : "default" => v if v.create == true
  }
  class_name = "vpcInstPol"
  dn         = "uni/fabric/vpcInst-${each.key}"
  content = {
    descr           = each.value.description
    name            = each.key
    deadIntvl       = each.value.peer_dead_interval
    #delayRestoreTmr = each.value.delay_restore_timer
  }
}
#resource "aci_vpc_domain_policy" "map" {
#  for_each = {
#    for v in [local.vpc_domain] : "default" => v if v.create == true
#  }
#  dead_intvl  = each.value.peer_dead_interval
#  description = each.value.description
#  name        = each.key
#}

```

Best regards

**Comment by scotttyso** [comment] 2023-09-19 20:12
@jorgenspange 

I didn't realize when I added the attribute that it was a 6.x vs 5.x attribute.

I have updated the module with the following:
```terraform
resource "aci_rest_managed" "vpc_domain_policy" {
  for_each = {
    for v in [local.vpc_domain] : "default" => v if v.create == true && length(
      regexall("^([5-9]|[1-9][0-9])\\.", local.apic_version)) > 0
  }
  class_name = "vpcInstPol"
  dn         = "uni/fabric/vpcInst-${each.key}"
  content = length(regexall("^([5-9]|[1-9][0-9])\\.", local.apic_version)) > 0 ? {
    deadIntvl       = each.value.peer_dead_interval
    delayRestoreTmr = each.value.delay_restore_timer
    descr           = each.value.description
    name            = each.key
  } : {
    deadIntvl       = each.value.peer_dead_interval
    descr           = each.value.description
    name            = each.key
  }
}
```

I am also going to update the fabric_wide_settings under system-settings to match this, as I like this approach better than what I was doing before. since this will be a breaking change, I performed the following to clear my state file.

```bash
tyscott@TYSCOTT-DESKTOP:~/terraform-cisco-modules/easy-aci/RICH/Asgard$ terraform state rm module.system_settings[\"default\"].aci_rest_managed.fabric_wide_
settings_5_2_3[\"default\"]
Removed module.system_settings["default"].aci_rest_managed.fabric_wide_settings_5_2_3["default"]
Successfully removed 1 resource instance(s).
tyscott@TYSCOTT-DESKTOP:~/terraform-cisco-modules/easy-aci/RICH/Asgard$
```

I then just re-applied the plan to use the aci_reset_managed.fabric_wide_settings resource.

I am waiting for the next release of the aci provider to push the module updates.  there are some fixes I am waiting for that they just closed out for me in the backlog.  When ACI Provider 2.11 releases I will push the module update.

**Comment by scotttyso** [comment] 2024-02-18 01:13
@jorgenspange , this issue was fixed back in November.  I am assuming you moved on to the Network as Code project at this point so I am closing this out.

**Closed as completed by scotttyso** 2024-02-18 01:13 UTC
